stages:
  - build
  - deploy

variables:
  DOCKER_COMPOSE_VERSION: "v2.23.3-desktop.2"

before_script:
  - apk add --no-cache docker-compose
  - docker-compose --version

build_and_push:
  stage: build
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose build
    - docker-compose up -d mongo
    - docker-compose run --rm server /bin/sh -c "npm run lint && npm run test"
    # - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN
    # - docker-compose push
  only:
    - main
# deploy:
#   stage: deploy
#   script:
#     - echo "Deploy multi-container application"
#   only:
#     - main
