stages:
  - build

build_dist:
  stage: build
  image: node:20.10.0-alpine  # Ensure npm and ng are available
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - frontend/node_modules/
      - /root/.npm/
  script:
    - if [ ! -f /usr/local/bin/ng ]; then npm install -g @angular/cli; fi # Cache Angular CLI
    - cd frontend
    - npm ci
    - ng build
  artifacts:
    paths:
      - frontend/dist/  # Frontend Angular client just copies /dist