stages:
  - deploy

variables:
  CI_DEBUG_SERVICES: "true"

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client docker-cli
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-add -l
    - ssh-keyscan -v -H $DROPLET_IP >> ~/.ssh/known_hosts

    - echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - docker-compose push
    - scp ./docker-compose.yaml root@$DROPLET_IP:/root/sang-logium/docker-compose.yaml
    - ssh root@$DROPLET_IP "cd /root/sang-logium && docker-compose pull && docker-compose up -d"
  only:
    - main
