stages:
  - build

build_dist:
  stage: build
  image: node:20.10.0-alpine  # Ensure npm and ng are available
  script:
    - npm install
    - ng build
  artifacts:
    paths:
      - dist/  # Frontend Angular client just copies /dist