stages:
  - build
  - test
  - lint

variables:
  DOCKER_IMAGE_NAME: munrhalls/sang-logium-frontend

build:
  stage: build
  script:
    - cd frontend
    - docker build -t $DOCKER_IMAGE_NAME .

test:
  stage: test
  script:
    - docker run $DOCKER_IMAGE_NAME npm test

lint:
  stage: lint
  script:
    - docker run $DOCKER_IMAGE_NAME npm run lint
