stages:
  - deploy

variables:
  CI_DEBUG_SERVICES: "true"

deploy:
  stage: deploy
  image: docker:25.0.3-dind-alpine3.19
  services:
    - docker:dind
  before_script:
    - apk add --no-cache openssh-client docker-cli docker-compose
    - apk add --no-cache netcat-openbsd
    - nc -zv $DROPLET_IP 22
    - docker version
    - echo "$DOCKER_HUB_ACCESS_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - chmod +x /usr/local/bin/docker-compose
    - export IMAGE_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

    - eval $(ssh-agent -s)

    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-add -l

    - ssh-keyscan -vvv $DROPLET_IP >> /root/~/.ssh/known_hosts || echo "ssh-keyscan failed with exit code $?"
    - chmod 644 ~/.ssh/known_hosts

  script:
    - scp ./docker-compose.yaml root@$DROPLET_IP:/root/sang-logium/docker-compose.yaml
    - ssh root@$DROPLET_IP "sed -i '/^IMAGE_TAG=/c\\IMAGE_TAG=${IMAGE_TAG}' /root/sang-logium/.env && cd /root/sang-logium && docker-compose pull && docker-compose up -d"

  only:
    - main
