stages:
  - build
  - test

build:
  stage: build
  script:
    - docker-compose build sang-logium-frontend

test:
  stage: test
  script:
    - docker-compose up -d sang-logium-frontend
    - docker-compose exec sang-logium-frontend npm test
    - docker-compose exec sang-logium-frontend npm run lint
    - docker-compose down
