stages:
  - build
  - test

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - apk add --no-cache docker-compose  # Install docker-compose on Alpine-based images

build:
  stage: build
  image: docker:latest  # Using Docker image which includes Docker CLI
  script:
    - docker-compose build sang-logium-frontend

test:
  stage: test
  image: docker:latest
  script:
    - docker-compose up -d sang-logium-frontend
    - docker-compose exec sang-logium-frontend npm test
    - docker-compose exec sang-logium-frontend npm run lint
    - docker-compose down
