stages:
  - prepare
  - test
  - lint
  - build
  - dockerize

prepare:
  stage: prepare
  image: node:20.10.0-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm ci
    - npm install --save-dev @angular/cli
  artifacts:
    paths:
      - frontend/node_modules/

unit_test_frontend:
  stage: test
  image: node:20.10.0-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - apk update && apk add chromium
    - export CHROME_BIN=/usr/bin/chromium-browser  # Set CHROME_BIN to the path of the installed Chromium binary
    - npx ng test --no-watch --no-progress --browsers=ChromeHeadless


lint_frontend:
  stage: lint
  image: node:20.10.0-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm run lint

build_dist:
  stage: build
  image: node:20.10.0-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npx ng build
  artifacts:
    paths:
      - frontend/dist/

dockerize_frontend:
  stage: dockerize
  image: docker:24.0.7-dind
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose -f docker-compose.yaml build sang-logium-frontend
  only:
    - main


# deploy frontend
# TODO Docker tag image
# TODO Push image to dockerhub
# TODO ssh into