version: "3.8"

services:
  frontend:
    image: munrhalls/sang-logium-frontend:${IMAGE_TAG}
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - PORT=80

  server:
    image: munrhalls/sang-logium-server:${IMAGE_TAG}
    depends_on:
      - database
    networks:
      - app-network
    restart: unless-stopped
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@database:27017/${MONGO_INITDB_DATABASE}"

  database:
    restart: always
    image: munrhalls/sang-logium-database:${IMAGE_TAG}
    volumes:
      - ./database/data/db:/data/db
    ports:
      - "27017-27017:27017-27017"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10m
      timeout: 10s
      retries: 3
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

networks:
  app-network:
    driver: bridge
