version: "3.8"

services:
  nginx:
    image: munrhalls/sang-logium-revproxy:${IMAGE_TAG}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - server
      - database
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    environment:
      - PORT=80
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG
    image: munrhalls/sang-logium-frontend:${IMAGE_TAG}
    volumes:
      - /frontend/node_modules:/app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG
    image: munrhalls/sang-logium-server:${IMAGE_TAG}
    volumes:
      - /server/node_modules:/app/node_modules
    depends_on:
      - database
    networks:
      - app-network
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      DATA_SERVER_NODE_ENV: ${DATA_SERVER_NODE_ENV}
      DATA_SERVER_PORT: ${DATA_SERVER_PORT}

  database:
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG
    image: munrhalls/sang-logium-database:${IMAGE_TAG}
    # volumes:
    #   - ./database/data/db:/data/db
    expose:
      - 27017
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10m
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

networks:
  app-network:
    driver: bridge
