version: "3.8"

services:
  database:
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
    image: mongo:5.0.23
    volumes:
      - ./database/data/db:/data/db
    # env_file:
    #   - ./database/.env
    expose:
      - 27017
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10m
      timeout: 10s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: munrhalls/sang-logium-server:${GENERATED_TAG:-local-development-version}
    depends_on:
      - database
    # env_file:
    #   - ./server/.env
    networks:
      - app-network
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      DATA_SERVER_NODE_ENV: ${DATA_SERVER_NODE_ENV}
      DATA_SERVER_PORT: ${DATA_SERVER_PORT}

  frontend:
    environment:
      - PORT=80
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # The image tag defaults to "local-development-version" locally, and GENERATED_TAG in CI/CD production runtime
    image: munrhalls/sang-logium-frontend:${GENERATED_TAG:-local-development-version}
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
