version: "3.8"

services:
  # mongo:
  #   restart: always
  #   image: mongo:5.0.23
  #   volumes:
  #     - ./database/data/db:/data/db
  #   env_file:
  #     - ./database/.env
  #   expose:
  #     - 27017
  #   networks:
  #     - mongo-network
  #   healthcheck:
  #     test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
  #     interval: 10m
  #     timeout: 10s
  #     retries: 3
  # restart: unless-stopped

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mongo
  #   env_file:
  #     - ./server/.env
  #   networks:
  #     - mongo-network
  # restart: unless-stopped

  sang-logium-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: munrhalls/sang-logium-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  mongo-network:
    driver: bridge
  app-network:
    driver: bridge
