version: "3.8"

services:
  mongo:
    restart: always
    image: mongo:5.0.23
    volumes:
      - ./database/data/db:/data/db
    env_file:
      - ./database/.env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    #   - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    expose:
      - 27017
    networks:
      - mongo-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10m
      timeout: 10s
      retries: 3

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    # ports:
    #   - "${PORT}:8443"
    # environment:
    #   - MONGO_URI=${MONGO_URI}
    #   - NODE_ENV=${NODE_ENV}
    networks:
      - mongo-network

  # angular-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - .:/app
  #   command: ["ng", "serve", "--host", "0.0.0.0"]

networks:
  mongo-network:
    driver: bridge
