version: v2.23.3-desktop.2

services:
  mongo:
    restart: always
    image: mongo:5.0.23
    volumes:
      - ./data/db:/data/db
    env_file:
      - ./backend/database/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    expose:
      - 27017
    networks:
      - mongo-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10m
      timeout: 10s
      retries: 3

  server:
    build:
      context: ./backend/server
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    depends_on:
      - mongo
    env_file:
      - ./backend/server/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
