version: "3.8"

services:
  mongo:
    restart: always
    image: mongo:5.0.23
    volumes:
      - ./database/data/db:/data/db
    # env_file:
    #   - ./database/.env
    expose:
      - 27017
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10m
      timeout: 10s
      retries: 3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongo
    # env_file:
    #   - ./server/.env
    networks:
      - app-network
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      DATA_SERVER_NODE_ENV: ${DATA_SERVER_NODE_ENV}
      DATA_SERVER_PORT: ${DATA_SERVER_PORT}

  sang-logium-frontend:
    environment:
      - PORT=80
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: munrhalls/sang-logium-frontend:${GENERATED_TAG}
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
# comment for commit
