name: CI for Dev to Main Merge

on:
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Triggering backend and frontend workflows"
